[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  VITE_SUPABASE_URL = "https://zjdqwsbbnavroipdqzuf.supabase.co"
  VITE_SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpqZHF3c2JibmF2cm9pcGRxenVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzk3OTcyMDgsImV4cCI6MjA5NTM3MzIwOH0.O5ohQv7VnLxZ-9ymPBgtQuf0w6JMthHpLL0eoW_x1lM"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
